name: Azure SQL – Deploy

on:
  workflow_dispatch:
    inputs:
      includeSeeds:
        description: "Include seed data? 1=yes, 0=no"
        required: true
        default: "1"
        type: choice
        options: ["1", "0"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install sqlcmd (ODBC + tools)
        run: |
          sudo ACCEPT_EULA=Y apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y mssql-tools18 unixodbc-dev
          echo '/opt/mssql-tools18/bin' >> $GITHUB_PATH

      - name: Verify sqlcmd
        run: sqlcmd -?

      - name: Build CI-safe deploy script (normalize, add GO around includes, strip CRLF and TRY/CATCH/TRAN)
        working-directory: db/scripts
        run: |
          awk '{
            line=$0
            sub(/\r$/, "", line)  # strip CR
            # drop outer control flow that conflicts with GO across files
            if (line ~ /^[[:space:]]*BEGIN[[:space:]]+TRY\b/i) next
            if (line ~ /^[[:space:]]*END[[:space:]]+TRY\b/i)   next
            if (line ~ /^[[:space:]]*BEGIN[[:space:]]+CATCH\b/i) next
            if (line ~ /^[[:space:]]*END[[:space:]]+CATCH\b/i)   next
            if (line ~ /^[[:space:]]*BEGIN[[:space:]]+TRAN\b/i)  next
            if (line ~ /^[[:space:]]*COMMIT[[:space:]]+TRAN\b/i) next
            if (line ~ /^[[:space:]]*ROLLBACK[[:space:]]+TRAN\b/i) next
            if (line ~ /^[[:space:]]*THROW\b/i) next

            # If this is a :r include (with optional leading spaces), normalize backslashes and surround with GO
            if (line ~ /^[[:space:]]*:r[[:space:]]+/) {
              gsub("\\\\","/", line)
              print "GO"
              print line
              print "GO"
            } else {
              print line
            }
          }' deploy_all.sql > deploy_all.ci.sql

          echo "==== First 80 lines ===="
          nl -ba deploy_all.ci.sql | sed -n '1,80p'
          echo "==== All include lines (post-normalization) ===="
          grep -nE '^[[:space:]]*:r[[:space:]]+' deploy_all.ci.sql || true
          echo "==== All GO lines around includes (sample) ===="
          nl -ba deploy_all.ci.sql | grep -n -E '^( *GO| *:r )' | sed -n '1,60p' || true

      - name: Run deploy_all.ci.sql
        working-directory: db/scripts
        env:
          SQLCMDPASSWORD: ${{ secrets.AZURE_SQL_PASSWORD }}
        run: |
          sqlcmd -C -b -I \
            -S "${{ secrets.AZURE_SQL_SERVER }}" \
            -U "${{ secrets.AZURE_SQL_USER }}" \
            -v DBName="${{ secrets.AZURE_SQL_DB }}" IncludeSeeds="${{ github.event.inputs.includeSeeds }}" \
            -i "./deploy_all.ci.sql"
