name: Azure SQL – Deploy

on:
  workflow_dispatch:
    inputs:
      includeSeeds:
        description: "Include seed data? 1=yes, 0=no"
        required: true
        default: "1"
        type: choice
        options: ["1", "0"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install sqlcmd (ODBC + tools)
        run: |
          sudo ACCEPT_EULA=Y apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y mssql-tools18 unixodbc-dev
          echo '/opt/mssql-tools18/bin' >> $GITHUB_PATH

      - name: Verify sqlcmd
        run: sqlcmd -?

      - name: Build CI-safe deploy script (normalize :r, strip CRLF, drop TRY/CATCH/TRAN)
        working-directory: db/scripts
        run: |
          awk '{
            line=$0
            sub(/\r$/, "", line)                                     # strip CR
            if (line ~ /^[[:space:]]*:r[[:space:]]+/) gsub("\\\\","/",line) # normalize include paths
            # skip control-flow lines that conflict with GO in includes
            if (line ~ /^[[:space:]]*BEGIN[[:space:]]+TRY\b/i) next
            if (line ~ /^[[:space:]]*END[[:space:]]+TRY\b/i) next
            if (line ~ /^[[:space:]]*BEGIN[[:space:]]+CATCH\b/i) next
            if (line ~ /^[[:space:]]*END[[:space:]]+CATCH\b/i) next
            if (line ~ /^[[:space:]]*BEGIN[[:space:]]+TRAN\b/i) next
            if (line ~ /^[[:space:]]*COMMIT[[:space:]]+TRAN\b/i) next
            if (line ~ /^[[:space:]]*ROLLBACK[[:space:]]+TRAN\b/i) next
            if (line ~ /^[[:space:]]*THROW\b/i) next
            print line
          }' deploy_all.sql > deploy_all.ci.sql

          echo "==== First 40 lines (sanity) ===="
          nl -ba deploy_all.ci.sql | sed -n '1,40p'
          echo "==== Include lines (post-normalization) ===="
          grep -nE '^[[:space:]]*:r[[:space:]]+' deploy_all.ci.sql || true

      - name: Run deploy_all.ci.sql
        working-directory: db/scripts
        env:
          SQLCMDPASSWORD: ${{ secrets.AZURE_SQL_PASSWORD }}
        run: |
          sqlcmd -C -b -I \
            -S "${{ secrets.AZURE_SQL_SERVER }}" \
            -U "${{ secrets.AZURE_SQL_USER }}" \
            -v DBName="${{ secrets.AZURE_SQL_DB }}" IncludeSeeds="${{ github.event.inputs.includeSeeds }}" \
            -i "./deploy_all.ci.sql"
